# Generated by Django 4.0.4 on 2022-06-07 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Код')),
                ('user_id_messenger', models.IntegerField(blank=True, null=True, verbose_name='Id мессенджера пользователя')),
                ('user_activation_key', models.CharField(max_length=32, verbose_name='Код активации бота')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Никнейм пользователя')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Бот',
            },
        ),
    ]
