# Generated by Django 4.0.4 on 2022-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_cod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotmodel',
            name='code',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='telegrambotmodel',
            name='user_id_messenger',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
