# Generated by Django 4.0.4 on 2022-05-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_cod', '0003_alter_telegrambotmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
