# Generated by Django 4.0.4 on 2022-06-07 14:14

import apps.face_auth.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDescriptionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('photo', models.ImageField(upload_to=apps.face_auth.models.upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Описание лица',
                'verbose_name_plural': 'Описание лиц',
            },
        ),
    ]
