# Generated by Django 4.0.4 on 2022-06-07 15:50

import apps.face_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth', '0003_remove_facedescriptionsmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedescriptionsmodel',
            name='photo',
            field=models.ImageField(default=0, upload_to=apps.face_auth.models.upload_to),
            preserve_default=False,
        ),
    ]
